### ISSUE TITLE
Update Snaps documentation for v12.4

### ISSUE THREAD

**Issue by ziad-saab** [MetaMask/metamask-docs#1522]
Many new features were added and/or updated.

Look here to find the new additions and write docs >> https://github.com/MetaMask/metamask-extension/pulls?q=is%3Apr+is%3Aclosed+label%3Ateam-snaps-platform+

- [x] metamask/metamask-extension#26682
- [x] metamask/metamask-extension#26570
- [x] metamask/metamask-extension#26181
- [x] metamask/metamask-extension#25413
- [x] metamask/metamask-extension#25670 (update screenshots)
- [x] metamask/metamask-extension#26675
- [x] metamask/metamask-extension#26709
- [ ] metamask/snaps#2413
- [ ] metamask/metamask-extension#25505

AC:
- New documentation for what will be added in v12.4
- Update documentation for anything that will change in v12.4
