### ISSUE TITLE
Docusaurus plugin

### ISSUE THREAD

**Issue by BelfordZ** [MetaMask/metamask-docs#719]
## Stage 1 

Setup the most basic plugin to make it easy to create the reference docs & update them inside api-specs & view the changes.

 - [x] make a new repo for the plugin (metamask/docusaurus-openrpc)
 - [x] loadContent - fetch / read the openrpc file, deref & validate it
 - [x] contentLoaded - run openrpc-to-markdown and addRoute / createData
 - [x] use injectHtml tags to add custom CSS required to make the generated markdown look a bit better
 - [x] Plugin to build the api reference on yarn build / start
 - [x] Ability to watch a directory / openrpc file from another project
   - [x] api specs to have a watch command
 - [x] Add a link in the top nav for the generated reference docs
 
 ## Stage 2
 
 Improve the generated content. Most of this work will happen inside the [plugin repo](https://github.com/MetaMask/docusaurus-openrpc)

 - [x] (maybe) use react components all the way down rather than using markdown
   - [x] spike on adding [@open-rpc/docs-react](https://github.com/open-rpc/docs-react)
 - [ ] structure changes
   - [ ] split into methods and types
   - [ ] group methods by tags / prefixes (eth_ vs wallet_) and make into categories in sidebar
 - [x] resolve duplicate methods (eth accounts in there twice)
 - [x] don't collapse the methods
 
  ## Stage 3
  
  Add interactivity to the generated docs
  
  - [ ] spike on integrating [@open-rpc/inspector](https://github.com/open-rpc/inspector)
  - [x] UI for calling the methods 
  - [x] methods that include examples are easily prefilled

**Comment by shanejonas** [comment]
# stage 2
restructure to types and methods
themes
ui/react components
rendering

# stage 3

interactivity
runnable examples
etc

**Comment by kenhkan** [comment]
From standup:
- Create tickets:
- 1. Live editing window.ethereum.request box
- 2. Enable other JSON-RPC transports / window.ethereum.request configurable
