### ISSUE TITLE
openrpc docs plugin pre-launch todo list

### ISSUE THREAD

**Issue by BelfordZ** [MetaMask/metamask-docs#779]
## current branches

  - metamask-docs:
    - `openrpc-sidebar-support`
  - docusaurus-openrpc:
    - `sidebar-support`

---

## Pre-launch todo:

 - [x] MetaMask/metamask-docs#786
 - [ ] json-schema improvements to api-specs
   - [x] MetaMask/api-specs#146
   - [x] MetaMask/api-specs#147
   - [x] MetaMask/api-specs#148
   - [x] MetaMask/api-specs#155
 - [x] #797
 - [x] MetaMask/metamask-docs#783
  --- 
  ## post launch todo
 - [x] #798
 - [ ] MetaMask/metamask-docs#784
 - [ ] MetaMask/metamask-docs#785
 - [ ] content-docs plugin merge wrapped up
   - [x] MetaMask/metamask-docs#781
   - [x] #799
   - [ ] MetaMask/metamask-docs#782
   - [x] MetaMask/metamask-docs#783
  - [ ] MetaMask/api-specs#153
  - [ ] MetaMask/api-specs#154
  - [ ] MetaMask/api-specs#149
  - [ ] MetaMask/api-specs#150
  - [ ] MetaMask/api-specs#151
  - [ ] MetaMask/api-specs#152

**Comment by vandan** [comment]
Looks like there's a side-effect that's causing some changes to the formatting of the footer:
<img width="1561" alt="Screenshot 2023-06-09 at 7 33 03 AM" src="https://github.com/MetaMask/metamask-docs/assets/1643618/1dcd0782-9767-459e-a452-1f3011e3ae8f">

**Comment by kenhkan** [comment]
From standup: The post-launch todos are not related to each other. They will be closed separately.
